/** 
* ===================================================================================
* @className        PA_CalloutService_Test
* @description      Clase test para PA_CalloutService
* @author           Curetti Santiago
* @email            santiago.curetti@capgemini.com
* @version          V0.1
* @dateCreated      2023/03/11
* ==============================================================================================================================
*/
public with sharing class PA_CalloutService_Test {
    public PA_CalloutService_Test() {

    }
}