/** 
* ===================================================================================
* @className        PA_SchedulableCharacters_Test
* @description      Clase test para PA_SchedulableCharacters
* @author           Curetti Santiago
* @email            santiago.curetti@capgemini.com
* @version          V0.1
* @dateCreated      2023/03/11
* ==============================================================================================================================
*/
public with sharing class PA_SchedulableCharacters_Test {
    public PA_SchedulableCharacters_Test() {

    }
}